// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDAgEScBzVNU0urGc4NUIEUvL-qOyBGk',
    appId: '1:594023808745:web:7eb0f9d032c178adc53a78',
    messagingSenderId: '594023808745',
    projectId: 'ayavoy-dd7eb',
    authDomain: 'ayavoy-dd7eb.firebaseapp.com',
    databaseURL: 'https://ayavoy-dd7eb-default-rtdb.firebaseio.com',
    storageBucket: 'ayavoy-dd7eb.appspot.com',
    measurementId: 'G-LMQ89BZ5RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2fG5lRe69C9TIC8jNovLyn5RsHi4IjYw',
    appId: '1:594023808745:android:cafbae1e05080245c53a78',
    messagingSenderId: '594023808745',
    projectId: 'ayavoy-dd7eb',
    databaseURL: 'https://ayavoy-dd7eb-default-rtdb.firebaseio.com',
    storageBucket: 'ayavoy-dd7eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAhDnP--x8IGe99M9ugebb4K2hDmglnlM',
    appId: '1:594023808745:ios:46d26c4d17b2b7ecc53a78',
    messagingSenderId: '594023808745',
    projectId: 'ayavoy-dd7eb',
    databaseURL: 'https://ayavoy-dd7eb-default-rtdb.firebaseio.com',
    storageBucket: 'ayavoy-dd7eb.appspot.com',
    iosBundleId: 'bundle.id',
  );
}
