// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDAgEScBzVNU0urGc4NUIEUvL-qOyBGk',
    appId: '1:594023808745:web:7eb0f9d032c178adc53a78',
    messagingSenderId: '594023808745',
    projectId: 'ayavoy-dd7eb',
    authDomain: 'ayavoy-dd7eb.firebaseapp.com',
    databaseURL: 'https://ayavoy-dd7eb-default-rtdb.firebaseio.com',
    storageBucket: 'ayavoy-dd7eb.appspot.com',
    measurementId: 'G-LMQ89BZ5RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-C4KWBH1dg-lJfpuiaqqqA_1p9mDkgY',
    appId: '1:333078895460:android:421cbc02755c31c945f871',
    messagingSenderId: '333078895460',
    projectId: 'ayavoy-32f89',
    databaseURL: 'https://ayavoy-32f89-default-rtdb.firebaseio.com',
    storageBucket: 'ayavoy-32f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGs_4TWN8kuxFEWA7YXy0mMJnpY9Vn5zE',
    appId: '1:333078895460:ios:63d6af51c3e1a8f445f871',
    messagingSenderId: '333078895460',
    projectId: 'ayavoy-32f89',
    databaseURL: 'https://ayavoy-32f89-default-rtdb.firebaseio.com',
    storageBucket: 'ayavoy-32f89.appspot.com',
    androidClientId: '333078895460-2t4ob10td8jpa1vavcg54p1mhsp9787j.apps.googleusercontent.com',
    iosClientId: '333078895460-7mpf85tvbsj44732mo7rp14ftseb8cma.apps.googleusercontent.com',
    iosBundleId: 'bundle.id',
  );

}